#!/usr/bin/env sh
set -eu

: "${MARIADB_ROOT_PASSWORD:?MARIADB_ROOT_PASSWORD is required}"
: "${STAGING_DB_NAME:?STAGING_DB_NAME is required}"
: "${STAGING_DB_USER:?STAGING_DB_USER is required}"
: "${STAGING_DB_PASSWORD:?STAGING_DB_PASSWORD is required}"
: "${DEV_DB_NAME:?DEV_DB_NAME is required}"
: "${DEV_DB_USER:?DEV_DB_USER is required}"
: "${DEV_DB_PASSWORD:?DEV_DB_PASSWORD is required}"

mariadb \
  -uroot \
  -p"${MARIADB_ROOT_PASSWORD}" \
  -e "CREATE DATABASE IF NOT EXISTS \`${STAGING_DB_NAME}\`; \
      CREATE DATABASE IF NOT EXISTS \`${DEV_DB_NAME}\`; \
      CREATE USER IF NOT EXISTS '${STAGING_DB_USER}'@'%' IDENTIFIED BY '${STAGING_DB_PASSWORD}'; \
      CREATE USER IF NOT EXISTS '${DEV_DB_USER}'@'%' IDENTIFIED BY '${DEV_DB_PASSWORD}'; \
      ALTER USER '${STAGING_DB_USER}'@'%' IDENTIFIED BY '${STAGING_DB_PASSWORD}'; \
      ALTER USER '${DEV_DB_USER}'@'%' IDENTIFIED BY '${DEV_DB_PASSWORD}'; \
      GRANT ALL PRIVILEGES ON \`${STAGING_DB_NAME}\`.* TO '${STAGING_DB_USER}'@'%'; \
      GRANT ALL PRIVILEGES ON \`${DEV_DB_NAME}\`.* TO '${DEV_DB_USER}'@'%'; \
      FLUSH PRIVILEGES;"

echo "MariaDB env DB provisioning complete: ${STAGING_DB_NAME}, ${DEV_DB_NAME}"
